language: node_js
node_js:
  - 6
group: stable
dist: precise
os: linux
before_install:
  - sudo apt-get update -y
  - sudo apt-get install imagemagick graphicsmagick -y
  - sudo apt-get install mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 -y
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev g++ -y
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
before_script:
  - npm i node-gyp istanbul mocha typescript coveralls@2 -g
script: npm i; npm test
after_script: npm run cover && cat ./coverage/lcov.info | coveralls
