language: node_js
sudo: required
os: linux
dist: trusty
addons:
  apt:
    packages:
      - xvfb
      - libgl1-mesa-dri
      - libglapi-mesa
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
      - imagemagick
node_js:
  - 6
sudo: false
before_script:
  - sudo apt-get update
  - sudo apt-get install mesa-utils libosmesa6 ibcairo2-dev libgif-dev graphicsmagick -y
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm i node-gyp istanbul mocha typescript coveralls@2 -g
script: npm i; npm test
after_script: npm run cover && cat ./coverage/lcov.info | coveralls
