language: node_js
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - mesa-utils
      - xvfb
      - libgl1-mesa-dri
      - libglapi-mesa
      - libosmesa6
      - ibcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
      - graphicsmagick
node_js:
  - 6
sudo: false
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm i node-gyp istanbul mocha typescript coveralls@2 -g
script: npm i; npm test
after_script: npm run cover && cat ./coverage/lcov.info | coveralls
