language: node_js
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
    - ibcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++
    - graphicsmagick
node_js:
  - 6
sudo: false
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm i istanbul mocha typescript -g
script: npm install; npm test
after_script: npm run cover && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
